FROM python:3.10-slim
WORKDIR /app
COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY proto/ ./proto/
COPY server/ ./
RUN python -m grpc_tools.protoc -I./proto --python_out=. --grpc_python_out=. proto/story2audio.proto
EXPOSE 50051
CMD ["python", "main.py"]
