# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: story2audio.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11story2audio.proto\x12\x0bstory2audio\"Q\n\x0c\x41udioRequest\x12\x12\n\nstory_text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x0f\n\x07\x65motion\x18\x04 \x01(\t\"I\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2R\n\x0bStory2Audio\x12\x43\n\x08Generate\x12\x19.story2audio.AudioRequest\x1a\x1a.story2audio.AudioResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'story2audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=34
  _globals['_AUDIOREQUEST']._serialized_end=115
  _globals['_AUDIORESPONSE']._serialized_start=117
  _globals['_AUDIORESPONSE']._serialized_end=190
  _globals['_STORY2AUDIO']._serialized_start=192
  _globals['_STORY2AUDIO']._serialized_end=274
# @@protoc_insertion_point(module_scope)
